# 运行日志
Log:
  Dir: logs # 存储目录，非必要不修改
  Level: warn # 记录级别，debug|info|warn|error
  Target: stdout # 输出方式，both|file|null|stdout|stderr

# Wcf 服务
Wcf:
  Address: 127.0.0.1:7601 # 若使用外部地址，请删除 WcfBinary 选项 【改成调用dll文件了】
  MsgPrint: false # 是否将消息输出到控制台，可用于调试
  MsgStore: true # 是否将消息写入数据库，用于防撤回和统计
  MsgStoreDays: 7 # 启动时清理n天前的消息，0 表示不清理
  SdkLibrary: sdk.dll # wcf 二进制文件路径，留空则不托管（Linux 必须留空）

# Web 服务
Web:
  Address: 0.0.0.0:7600 # 监听地址，外网访问修改为 0.0.0.0:7600
  PushUrl: "" # 消息推送地址，一行一个，留空则不启用
  Storage: storage # 附件存储路径，非必要不修改
  Swagger: true # 是否启用内置接口文档和调试工具
  Token: "123456" # 使用 Token 验证请求，留空则不验证


# 其他配置
Others:
  SignInPoint: 10 # 签到积分
  PicPoint: 1 # 获取图片积分
  VideoPoint: 2 # 获取视频积分

## 其它功能关键词配置
FunctionKeyWord:
  # 触发美女视频关键词
  videoWord:
    - '视频'
    - '美女视频'
    - '成人视频'
    - '18禁'

  # 触发疯狂星期四文案关键词
  # 触发舔狗日记关键词
  dogWord:
    - '舔狗日记'
    - '舔我'

ApiServer:
  # 摸鱼日记API
  fishApi: 'https://dayu.qqsuu.cn/moyuribao/apis.php?type=json'
  # 摸鱼视频API
  fishVideoApi: 'http://dayu.qqsuu.cn/moyuribaoshipin/apis.php?type=json'
  # 舔狗日记API
  dogApi: 'https://apis.tianapi.com/tiangou/index?key={}'
  # 内涵段子API
  jokeApi: 'https://dayu.qqsuu.cn/neihanduanzi/apis.php'
  # 星座运势
  constellationApi: 'https://dayu.qqsuu.cn/xingzuoyunshi/apis.php'

  # 美女图片接口API
  picApi:
    - 'https://api.btstu.cn/sjbz/api.php?lx=dongman&format=images&method=mobile&lx=meizi'
    - 'https://cdn.seovx.com/?mom=302'
    - 'https://tuapi.eees.cc/api.php?category=meinv&px=m&type=302'
    - 'http://3650000.xyz/api/'

  # 视频API配置
  videosApi:
    - 'https://api.kuleu.com/api/xjj?type=v'
    - 'http://api.yujn.cn/api/heisis.php'
    - 'http://api.yujn.cn/api/xjj.php'
    - 'http://api.yujn.cn/api/zzxjj.php'
    - 'https://api.yujn.cn/api/manzhan.php'
    - 'http://api.yujn.cn/api/rewu.php?type=video'
    - 'http://api.ovoe.top/API/hbss.php'
    - 'http://abc.gykj.asia/API/hbss.php'
    - 'http://api.yujn.cn/api/hanfu.php?type=video'
    - 'http://abc.gykj.asia/API/gzhf.php'
    - 'http://www.yujn.cn/api/heisis.php'
    - 'http://api.yujn.cn/api/manyao.php?type=video'
    - 'https://api.shenke.love/api/mnsp.php?msg=my&type=video'
    - 'http://api.yujn.cn/api/COS.php?type=video'
    - 'http://abc.gykj.asia/API/ntCOS.php'
    - 'http://api.yujn.cn/api/jksp.php?type=video'
